import modal from './modules/modal';
import slider from './modules/slider';
import sendForm from './modules/sendForm';
import accordeon from './modules/accordeon';
import swiperCard from './modules/swiperCard';
import scrollArrow from './modules/scrollArrow';
import abouttCompany from './modules/abouttCompany';
import mobileMenu from './modules/mobileMenu';
import stepsWork from './modules/stepsWork';
import advantages from './modules/advantages';

modal();
slider();
sendForm();
accordeon();
swiperCard();
mobileMenu();
scrollArrow();
abouttCompany();
stepsWork();
advantages();